### ISSUE TITLE
TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by lsiden** [wearefractal/vinyl-fs#78]
gulp task watch-app throws this exception after several successful builds:

    [00:59:23] Starting 'build-code'...
    [00:59:23] /********************* Build Code *********************/
    [00:59:23] Executed tasks:
    [00:59:23]  css
    [00:59:23]  requirejs
    [00:59:23]  angular-templatecache
    [00:59:23]  vendor-scripts
    [00:59:23]  index-create
    [00:59:23] Finished 'build-code' after 5.27 ms

    TypeError: Arguments to path.resolve must be strings
        at Object.exports.resolve (path.js:313:15)
        at Object.exports.relative (path.js:371:18)
        at File.Object.defineProperty.get (/home/vagrant/pah/cpportal/node_modules/gulp-requirejs/node_modules/gulp-util/node_modules/vinyl/index.js:121:17)
        at DestroyableTransform.saveFile [as _transform] (/home/vagrant/pah/cpportal/node_modules/gulp/node_modules/vinyl-fs/lib/dest/index.js:36:48)
        at DestroyableTransform.Transform._read (/home/vagrant/pah/cpportal/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
        at DestroyableTransform.Transform._write (/home/vagrant/pah/cpportal/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
        at doWrite (/home/vagrant/pah/cpportal/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
        at writeOrBuffer (/home/vagrant/pah/cpportal/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
        at DestroyableTransform.Writable.write (/home/vagrant/pah/cpportal/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
        at write (/home/vagrant/pah/cpportal/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)

I have found other complaints about this but cannot tell whether they're related.  I am also not sure which project this should be reported to: vinyl or vinyl-fs or something else on the stack.

In case this helps:

    vagrant@vagrant-ubuntu-trusty-64:~/pah/cpportal$ npm ls vinyl
    PAH@0.1.1 /home/vagrant/pah/cpportal
    ├─┬ gulp@3.9.0
    │ └─┬ vinyl-fs@0.3.13
    │   └── vinyl@0.4.6 
    ├─┬ gulp-angular-protractor@0.0.2
    │ └─┬ gulp-protractor@0.0.11
    │   └─┬ gulp-util@2.2.20
    │     └── vinyl@0.2.3 
    ├─┬ gulp-requirejs@0.1.3
    │ └─┬ gulp-util@2.2.20
    │   └── vinyl@0.2.3 
    └─┬ gulp-util@3.0.6
      └── vinyl@0.5.0 

    vagrant@vagrant-ubuntu-trusty-64:~/pah/cpportal$ npm ls vinyl-fs
    PAH@0.1.1 /home/vagrant/pah/cpportal
    └─┬ gulp@3.9.0
      └── vinyl-fs@0.3.13

**Comment by contra** [comment]
Can I see the code that triggered this?

**Comment by lsiden** [comment]
Part of the problem is that the stack trace only prints 10 frames.  Do you know how to tell gulp (or node?) that I want it to print the whole stack?

**Comment by contra** [comment]
@lsiden I think theres a module called longjohn for that

**Comment by shinnn** [comment]
@lsiden Could you show us the option that object you passes to `gulp-requirejs` plugin?

**Comment by contra** [comment]
As far as I can tell you are passing something bad to gulp.dest and it is failing to join it to the file path. Check your arguments, and I'll keep this open as a reminder that we need a better error message on invalid dest args

**Comment by contra** [comment]
Yep, probably options.base that is bad
